### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by coby7016** [giodestone/Emotion-Recognition#1]
can't find the images nor the directory "MUG images"

**Comment by giodestone** [comment]
Hello,

Thank you for submitting this issue.

I have fixed the issue in commit [fe4bf50](https://github.com/giodestone/Emotion-Recognition/commit/fe4bf502f19c8b507c71b563f81c142b369be0d5). Please pull from origin. You will also have to download the Cohn-Kanade+ set ([download here](https://github.com/spenceryee/CS229)), and place the folder named _CK+_ in the _Source/_ directory.

If you wish to use the MUG dataset, you would need to request MUG directly and place the files into the solution. [Instructions for requesting the data are here](https://mug.ee.auth.gr/fed/). This dataset is only available for non-commercial use, and will only accept requests from academic email addresses.

If you wish to explore more sets, there are [some more mentioned here](https://analyticsindiamag.com/top-8-datasets-available-for-emotion-detection/), but you would have to extend the `MachineLearning.GetLabel` function to work with them.

Please let me know if this resolves your issue or if you have further questions.

**Comment by giodestone** [comment]
Due to inactivity, this issue will be closed. Please feel free to reopen/comment should you have any further questions/issues.

**Comment by coby7016** [comment]
Thanks for the fix, unfortunately I was not able to access the data because
I'm a retired engineer and not in academic.

Again thanks
